name: Testing
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.16
        uses: actions/setup-node@v3
        with:
          node-version: 16.16
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: npm run coverage
